### ISSUE TITLE
Dead code ?

### ISSUE THREAD

**Issue by AlexP20000** [UBO-Open-factory/TOCIO-Back-office#22]
in file **backoffice/basic/components/cartesWidget.php**
`$l_STR_BtnAjoutcarte` is never used, plese update or delete
`$l_STR_iconDeplacer` is never used, plese update or delete
`$l_STR_BtnAjoutmethod` is never used, plese update or delete

Is the above code usefull ?
```
$contents[] = "<legend class='col-1'> </legend>";
$contents[] = "<legend class='col-2'> </legend>";
$contents[] = "<legend class='col-1'> </legend>";
```

**Comment by SerReginald** [comment]
Yes, it's used to correctly form the tab , the 4 last col need to be clean ,  I merged the 3 lines in one
